# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html

#fos_rest: ~

#fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
#            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }

#fos_rest:
#  routing_loader:
#    default_format: json
#    include_format: false
#  body_listener: true
#  format_listener:
#    enabled: true
#    rules:
#      - { path: '^/api/', priorities: ['json'], fallback_format: json, prefer_extension: false }
#  param_fetcher_listener: true
#  access_denied_listener:
#    json: true
#  view:
#    view_response_listener: 'force'
#    formats:
#      json: true

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_converter:
        enabled: true
    body_listener: true
#        decoders:
#            json: fos_rest.decoder.json
#            xml: fos_rest.decoder.xml
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/', priorities: ['json', 'xml'], fallback_format: 'json', prefer_extension: true}
            - { path: '^/', priorities: ['json', 'html'], fallback_format: 'html' }
#    serializer:
#        serialize_null: true
    view:
        view_response_listener: 'force'
        templating_formats:
            html: false
    param_fetcher_listener: 'force'
