#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Controllers
todo.todo.rest.controller:
  resource: "Controller/Todo/TodoRestController.php"
  type:     annotation
  prefix:   /api/v1

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }