#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Controllers
todo.todo.rest.controller:
  resource: "Controller/Todo/TodoRestController.php"
  type:     annotation
  prefix:   /api/v1

user.user.rest.controller:
  resource: "Controller/User/UserRestController.php"
  type:     annotation
  prefix:   /api/v1

user.photo.rest.controller:
  resource: "Controller/User/UserPhotoRestController.php"
  type:     annotation
  prefix:   /api/v1

user.oauth.rest.controller:
  resource: "Controller/User/OauthRestController.php"
  type:     annotation
  prefix:   /api/v1

# Swagger
app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# FOS
fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_registration_check_email:
  path: register/check-email
  defaults: { _controller: FOSUserBundle:Registration:checkEmail }

# Sonata Media
gallery:
  resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
  prefix: /media/gallery

media:
  resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
  prefix: /media
